spring:
  application:
    name: xunyu-system
  profiles:
    active: core #加载xunyu_config项目中 的application-core.yml文件

server:
  port: 8005

feign:
   hystrix:
     enabled: true  #激活断路游

hystrix:
   command:
    default:
      execution:
        isolation:
         thread:
          timeoutInMilliseconds: 40000  #设置超时时间

