eureka:
  enabled: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
      #defaultZone: http://47.104.190.174:8001/eureka/
      registry-fetch-interval-seconds: 5 #拉取服务注册信息时间间隔,默认为30秒
  instance:
      lease-renewal-interval-in-seconds: 5 #心跳时间,默认为30秒
      lease-expiration-duration-in-seconds: 10 #若eureka server在这时间内没收到心跳则移除该instance,默认为90秒
spring:
  application:
    name: xunyu-zuul
  #profiles:
    #active: core//不需要加载xunyu_config中的配置文件
server:
  port: 8002
#配置zuul  服务网关
zuul:
  host:
      socket-timeout-millis: 60000
      connect-timeout-millis: 60000
      add-host-header: true #表示API网关在进行请求路由转发前为请求设置Host头信息。
  routes:
    api-provider:
      path: /provider/**
      service-id: xunyu-provider
    api-consume:
      path: /consume/**
      service-id: xunyu-consume
    api-shiro:
      path: /shiro/**
      service-id: xunyu-shiro
    api-crm:
      path: /crm/**
      service-id: xunyu-crm
    api-department:
      path: /department/**
      service-id: xunyu-department
    api-system:
       path: /sys/**
       service-id: xunyu-system
    api-zipkin:
       path: /zipkin/**
       service-id: xunyu-zipkin

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试。

ribbon:
  ReadTimeout: 60000 #获取或设置读取操作未完成时发生超时之前的毫秒数。
  ConnectTimeout: 60000 #客户端等待与服务器建立连接的时间（以毫秒计）
  MaxAutoRetries: 0 #在同一台服务器上重试的最大次数
  MaxAutoRetriesNextServer: 1 #要重试的下一个服务器的最大数量

#日志
logging:
   config: classpath:logback-medicare.xml