eureka:
  enabled: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
#      defaultZone: http://47.104.190.174:8001/eureka/
      registry-fetch-interval-seconds: 5 #拉取服务注册信息时间间隔,默认为30秒
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳时间,默认为30秒
    lease-expiration-duration-in-seconds: 10 #若eureka server在这时间内没收到心跳则移除该instance,默认为90秒
    prefer-ip-address: true  #地址使用该属性配置的IP
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

spring:
  application:
    name: xunyu-zuul
  http:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB

server:
  port: 8002
  tomcat:
    accept-count: 1000  #承受并发量
    max-threads: 1000
    max-connections: 2000

#配置zuul  服务网关
zuul:
  host:
      socket-timeout-millis: 60000
      connect-timeout-millis: 60000
      add-host-header: true #表示API网关在进行请求路由转发前为请求设置Host头信息。
      max-per-route-connections: 1000
      max-total-connections: 1000 #连接池
  routes:
    api-shiro:
      path: /shiro/**
      service-id: xunyu-shiro
    api-crm:
      path: /crm/**
      service-id: xunyu-crm
    api-system:
       path: /sys/**
       service-id: xunyu-system
    api-zipkin:
       path: /zipkin/**
       service-id: xunyu-zipkin
    api-tactics:
       path: /tactics/**
       service-id: xunyu-tactics
    api-log-manager:
       path: /log/**
       service-id: xunyu-log-manager
    api-operator:
       path: /oper/**
       service-id: xunyu-operator

#ribbon的权重负载策略 默认是轮询策略 com.netflix.loadbalancer.RoundRobinRule
#NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #断路器的超时时间需要大于ribbon的超时时间，不然不会触发重试。

ribbon:
  ReadTimeout: 60000 #获取或设置读取操作未完成时发生超时之前的毫秒数。
  ConnectTimeout: 60000 #客户端等待与服务器建立连接的时间（以毫秒计）
  MaxAutoRetries: 0 #在同一台服务器上重试的最大次数
  MaxAutoRetriesNextServer: 1 #要重试的下一个服务器的最大数量

logging:
  config: classpath:logback-medicare.xml
  #file: D:/Test/crm/crm.txt  #本地输出日志文件地址
  file: /opt/upload/msg-xunyu-all/catalina.base_IS_UNDEFINED/zuul.txt #计时、服务重启会被覆盖

#actuator  使用HTTP的各种请求来监管,审计,收集应用的运行情况
management:
  security:
    #是否启用安全
    enabled: false
endpoints:
  auditevents:  #陈列当前应用程序的审计事件信息。
     enabled: true
  autoconfig: #展示自动配置信息并且显示所有自动配置候选人以及他们“被不被”应用的原因。
     enabled: true
  beans:  #显示应用程序中所有Spring bean的完整列表。
     enabled: true
  configprops: #显示所有配置信息。
     enabled: true
  env: #陈列所有的环境变量。
     enabled: true
  flyway:
     enabled: true
  loggers: #显示和修改应用程序中的loggers配置。
     enabled: true
  metrics: #显示当前应用程序的“指标”信息。
     enabled: true
  liquibase: #显示已经应用的任何Liquibase数据库迁移。
     enabled: true
  mappings: #显示所有@RequestMapping的url整理列表。
     enabled: true
  trace: #显示跟踪信息（默认最后100个HTTP请求）。
     enabled: true
