spring:
  application:
    name: xunyu-tactics
  profiles:
    #active: pro #加载xunyu_profiles项目中 的application-core.yml文件
    active: dev #加载xunyu_profiles项目中 的application-dev.yml文件
    #active: local #加载xunyu_profiles项目中 的application-dev.yml文件

server:
  port: 8009

logging:
  level:
    src.main.java.com.xunyu.xunyu_tactics.dao: debug
    src.main.resources.mapper: debug
