package com.xunyu.xunyu_drools.address

import com.xunyu.xunyu_drools.model.Address;
import com.xunyu.xunyu_drools.model.fact.AddressCheckResult;

rule "Postcode should be filled with exactly 5 numbers"
    when
        address : Address(postcode != null, postcode matches "([0-9]{5})")
        checkResult : AddressCheckResult();
    then
        checkResult.setPostCodeResult(true);
		System.out.println("规则中打印日志：校验通过!");
end