#eureka:
  #client:
    #serviceUrl:
      #defaultZone: http://localhost:17081/eureka/
spring:
  application:
    name: xunyu-kafka
  #profiles:
    #active: core//不需要加载xunyu_config中的配置文件
server:
  port: 17086

#配置kafka
haiyang:
  kafka:
    binder:
      brokers: 192.168.3.5:9092
      zk-nodes: 192.168.3.5:2181
    group: test-group

  