spring:
  application:
    name: xunyu-shiro
  profiles:
    active: core #加载xunyu_config项目中 的application-core.yml文件
  redis:
    hostName: 127.0.0.1
    port: 6379
    timeOut: 1000
    maxIdle: 10
    maxWaitMillis: 15000
    testOnBorrow: true
    testWhileIdle: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:17081/eureka/
#  instance:
#      status-page-url: http://doctorppe.zhyaoshi.com/info
server:
  port: 17094

feign:
   hystrix:
     enabled: true  #激活断路游

hystrix:
   command:
    default:
      execution:
        isolation:
         thread:
          timeoutInMilliseconds: 4000  #设置超时时间




