spring:
  application:
    name: xunyu-department
  profiles:
    active: core #加载xunyu_config项目中 的application-core.yml文件

server:
  port: 8008

logging:
  level:
    src.main.java.com.xunyu.xunyu_department.dao: debug
    src.main.resources.mapper: debug

