spring:
 application:
  name: xunyu-actuator
 boot:
  admin:
   routes:
    endpoints: env,metrics,trace,dump,jolokia,info,configprops,logfile,refresh,flyway,liquibase,heapdump,hystrix.stream
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
      #defaultZone: http://47.104.190.174:8001/eureka/
  instance:
    prefer-ip-address: true  #地址使用该属性配置的IP
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

#测试,不使用密码
management.security.enabled: false

server:
 port: 8012