spring:
  application:
    name: xunyu-provider
  profiles:
    active: core #加载xunyu_config项目中 的application-core.yml文件

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:17081/eureka/
#  instance:
#      status-page-url: http://doctorppe.zhyaoshi.com/info
server:
  port: 17093
logging:
  config: classpath:logback-medicare.xml

feign:
   hystrix:
     enabled: true  #激活断路游

hystrix:
   command:
    default:
      execution:
        isolation:
         thread:
          timeoutInMilliseconds: 4000  #设置超时时间

