#数据库配置
db: 
  host: rm-m5e03vwf88v7vufn9ho.mysql.rds.aliyuncs.com
  #host: 118.190.192.244  和上面的是一个host
  port: 3306
  name: xunyu_db
  public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJZcCjn1viAr1f4994+1Do1i1xQnqDD3OupuyqG1Yq2EI+OV/enBB9ETdztE1ptXuU2lGq3eDHV22oat2BZXVIMCAwEAAQ==
#  public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIeMfolobgSenbQUUeSDQ/jvyjjJnBvu+v96HjaQma55SuDPMQxVI3GrtDcWmtKyj6RxvrPntQfblqWhCTn1p+kCAwEAAQ==

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: xunyu_db
    password: XunYu@DEV-DB
    #password: gDMiHwt8T05aHOGLyyUetgks2P320nacsVxrzYq3znT7/onzpcTQ7SkEhxce+dZ1A4Bu/Dzyq2AZX7yKqbhaNQ==
    url: jdbc:mysql://${db.host}:${db.port}/${db.name}?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&useSSL=false
    filter-class-names: stat
    filters: stat,config
    #初始化连接大小
    initial-size: 8
    #最小空闲连接数
    min-idle: 5
    #最大连接数
    max-active: 10
    #查询超时时间
    query-timeout: 60000
    #事务查询超时时间
    transaction-query-timeout: 60000
    #关闭空闲连接超时时间
    remove-abandoned-timeout: 1800


#mybatis配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml,classpath*:mapper/*Mapper.xml
#日志
logging:
  config: classpath:logback-medicare.xml
