spring:
 application:
  name: xunyu-actuator
 boot:
  admin:
   routes:
    endpoints: env,metrics,trace,dump,jolokia,info,configprops,logfile,refresh,flyway,liquibase,heapdump,hystrix.stream
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
      #defaultZone: http://47.104.190.174:8001/eureka/
  instance:
    prefer-ip-address: true  #地址使用该属性配置的IP
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

#测试,不使用密码
management.security.enabled: false

server:
 port: 8012

logging:
  config: classpath:logback-medicare.xml
  #file: D:/Test/crm/crm.txt  #本地输出日志文件地址
  file: /opt/upload/msg-xunyu-all/catalina.base_IS_UNDEFINED/actuator.txt #计时、服务重启会被覆盖

#actuator  使用HTTP的各种请求来监管,审计,收集应用的运行情况
management:
  security:
    #是否启用安全
    enabled: false
endpoints:
  auditevents:  #陈列当前应用程序的审计事件信息。
     enabled: true
  autoconfig: #展示自动配置信息并且显示所有自动配置候选人以及他们“被不被”应用的原因。
     enabled: true
  beans:  #显示应用程序中所有Spring bean的完整列表。
     enabled: true
  configprops: #显示所有配置信息。
     enabled: true
  env: #陈列所有的环境变量。
     enabled: true
  flyway:
     enabled: true
  loggers: #显示和修改应用程序中的loggers配置。
     enabled: true
  metrics: #显示当前应用程序的“指标”信息。
     enabled: true
  liquibase: #显示已经应用的任何Liquibase数据库迁移。
     enabled: true
  mappings: #显示所有@RequestMapping的url整理列表。
     enabled: true
  trace: #显示跟踪信息（默认最后100个HTTP请求）。
     enabled: true