spring:
  application:
    name: sgip-server
  cloud:
      stream:
        bindings:
          #配置自己定义的通道与哪个中间件交互
          customInput1: #Sink里的
            destination: xiaogege9 #生产主题
          #customOutput1:
            #destination: xiaogege3 #消费主题
        default-binder: kafka #默认的binder是kafka
  kafka:
    binder:
      brokers: localhost:9094
      zkNodes: localhost:2181
      minPartitionCount: 1 #最小分区
      autoCreateTopics: true
      autoAddPartitions: true #自动扩展分区
    consumer:
      group-id: consumer1
    producer:
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      client-id: ""

server:
  port: 8098

