spring:
  application:
    name: sgip-server
  profiles:
    #active: sgiptest #加载xunyu_sgip_config项目中 的application-sgiptest.yml文件  #测试
    active: sgipdev #加载xunyu_profiles项目中 的application-sgipdev.yml文件    #本地开发

server:
  port: 8013
  tomcat:
    tomcat:
      accept-count: 1000  #承受并发量
      max-threads: 1000
      max-connections: 2000

#日志
logging:
  config: classpath:logback.xml
  #file: D:/Test/sgip-client.log  #本地输出日志文件地址
  file: /opt/upload/msg-xunyu-all/catalina.base_IS_UNDEFINED/sgip-server.log