spring:
  application:
    name: xunyu-crm
  profiles:
    active: core #加载xunyu_config项目中 的application-core.yml文件

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
      #defaultZone: http://47.104.190.174:8001/eureka/
#  instance:
#      status-page-url: http://doctorppe.zhyaoshi.com/info
server:
  port: 8004

feign:
   hystrix:
     enabled: true  #激活断路游

hystrix:
   command:
    default:
      execution:
        isolation:
         thread:
          timeoutInMilliseconds: 40000  #设置超时时间

